
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c  "sleep 20 &&  python manage.py runserver 0.0.0.0:8000 "
    depends_on:
      - db

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    
  db:
    image: mysql:8.3
    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


    volumes:
      - ./mysql-data:/var/lib/mysql