# Generated by Django 5.0.7 on 2024-07-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
