# Generated by Django 5.0.7 on 2024-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='main/profile_pictures/'),
        ),
    ]
