# Generated by Django 5.1 on 2024-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lecturersubject_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='picture',
            field=models.ImageField(default='main/profile_pictures/default_pfp.jpeg', upload_to='main/profile_pictures/'),
        ),
    ]
